language: c
sudo: required
install:
  - bash -ex ocaml-ci-scripts/.travis-ocaml.sh
  - eval $(opam config env)
  - opam install js_of_ocaml menhir omake ounit
script:
  - omake
  - omake test
env:
  - OCAML_VERSION=4.02 OPAMYES=1
  - OCAML_VERSION=4.03 OPAMYES=1
  - OCAML_VERSION=4.04 OPAMYES=1
os:
  - linux
  # - osx
cache:
  directories:
    - "$HOME/.opam"
notifications:
  slack:
    secure: TPlZ9NzwxKvFeIYwvjCq9elp+gFxLaHJAiVGZgDxfEkQuqH1nHAw/EPtYLcR/gzbq7mJ8Xn5m7qaOJexqEN+IM80QMKsMcxGxmwJ7uGQO9LG4CyTMIHoYBw7MpwMBhQ0hWw/TBUh+z5ZZ2ycprBm2TLTgQAo45ZlDFH39uO50ILg7kwQAXCUXEc2dsKqhol7wxE0hSnSjkHDb2Vp3IKLrkaQG9OecME+gpmQBl0BV4wxH1qhMDNjjLj1+IkMpHQIui3SD5ZizLGdI5oouW0eaWVSFr8YCoK7bcp9vJEMv1x0FG3XdfqMsnV4bWSr6UPmWRtXljhLgqNry5lK1R4b4YAyiq7Maw2olM+l32Id14LgYCmMK1kX0qWHxVmWTSbQDx8euojrCE8oGJNuKdYgvGc3EfxhwbZQZG2BoSKNJEgVS3HorjAv4H2PorYJek2DynRa2opowIHDO9HMgPq4h4ocO7kTbaX6ESBNJXgjsiKgedFC2kOv6DnB7QVmBnP9IEs02wIE++H93I/Qy22WKkEMUDchmkGVbQHEsAo1gshc7pnKK8wKNkt6s38Dbaz70FJZt/6HlggwwkO6rvx+n92Fd0KO01KnN/8GM68zg2pnzL7oFdexDKmydja39n4sPi6QuVRjD3y3l3443fdM38U6lWPY/V7W9gyHEIkegjA=
