language: c
sudo: required
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam config env)
  - opam install menhir omake ounit
script:
  - omake test
env:
  - OCAML_VERSION=4.03 OPAMYES=1
os:
  - linux
cache:
  directories:
    - $HOME/.opam
