language: c
sudo: required
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam config env)
  - opam install menhir omake ounit
script:
  - omake test
env:
  - OCAML_VERSION=4.01 OPAMYES=1
  - OCAML_VERSION=4.02 OPAMYES=1
  - OCAML_VERSION=4.03 OPAMYES=1
os:
  - linux
cache:
  directories:
    - $HOME/.opam
notifications:
  slack:
    secure: NE/4y8E4dFZFj/Gy5GMboytV90VJ6yfLQrOvFf1A+Pavl8/JaWkCFtYYQNUBc9S/GBCDOcmMcSOXtNkGnSUQuhETyvlXSBd3jsfzfbszeVPnITiqYNVWbIJksfP4TkC6bChZnGdVfyjEBpPCtIr4uPdh+/SlGPjm7jxurziaZyrtWjOFrZ8Phf4CPdC9aGf1uVzL129ebsbEUBGYPqvuWFRz2jKaN1HmsEg7Wg/LdJw9dzgZCkj/DYY7Dm50Cdh0kfypm+THNpg+G2Num9IUx1Rs6fj7r0ZVY0MYkanGu2BqN16pdScCryuL0pBxXL7PjhgxQRzjb/YsIUcfzSnlV9A+DCJXyEuoOgcXSV5VRlINxOgfSFLN7KPqWm6DgBteK7mAzDLbDwwo9A15SPfphWaz61EuNr7DKVG3+c68IRjOlVhq7aTOQTQDz4NZfkgMs4bgH3Y6ruTaCFLgU330u+IvNNZZ9NXS0wTWmBAn+jG6R8LMYOmiG4udBTq2ik0fDAJj0eI0gUsQlNP96KLlJUb84bHFW3XQWKksIbVTvbzTSlDB574FJZmpKL0EBCYQuaVmFpSUVAIUI/5u2VPu2blIpPa/Knv07OpldyIARi889SHUexW3kcn5tnCAJlhND0d6q+8z8K6tjn9cRV1JJbmb3cVcbtsVePtHgXFLCck=
