language: c
sudo: required
install:
  - bash -ex .travis-ocaml.sh
  - eval $(opam config env)
  - opam install menhir omake ounit
script:
  - omake test
env:
  - OCAML_VERSION=4.03 OPAMYES=1
os:
  - linux
cache:
  directories:
    - $HOME/.opam
notifications:
  slack:
    secure: V7DqgVuNgBSziKaKJPjQ2fqSdt3Lyx/C3lZvGFX7E4C6jF5KnIsbvquW+WHk48XkpTerN8W5M8If666YfUgy9icgqVetQ1mxcbupM04oxHuu4awmtb5vJmx4/5jVeZs6UYVzgLOLJeG4jcVplFlHN/RxUjWw3dNgBaawwGCNbGtwYLQF6ZrmD87K8+pOUE3zLcEibOnDNK236tTrXIW+9NmZMDYeRr+T2RJn23uOpeV5rARa79adjJCsY7fLZIxZPeGQGnduJM/cYTvHWgnViKaW4x3qMOFvyu2sNeIaJbLpB5KVCdzHE5n9NZXMB3+Ve1C8AGfkzEToYdeidzyk9udaSYXQLBcI8VoIHhc6RataZa3ABAH/d2En2s+LATQfhfMJIfVCaP7j8TCRLf4IsHfxvMtMVV7IkXA4i7jaBVvManXBmkmkoFG+HcaPbw4XlPP/suhPHORJV2BM/1pZ24qNe9zS1kSmBJ4XD0Io7WnjWU5sAzoQIHo4onyvbSnEzS1vanokrtVAU5/ZuBhjXIog7YQYLYEr1UelNwIEuLxKcJwT8imhYZvqsSiJL0kWGw/tNYn/1FFTzIyDVVdC95RjaxfIoO0RB6w+udQo7OUPXUmOkyZZX4x5LVv77EdgU6KHz57f9Q2ByjqSJ3+s9RXmFWrI2OQK0pkm8aSamU4=
